// ============================================================
// IKSPI DIGITAL — DATA SIMULASI / DEMO
// ------------------------------------------------------------
// Seluruh data organisasi di file ini adalah data simulasi
// untuk keperluan prototype dan DEMO DAY. Data ini BUKAN data
// resmi IKSPI Kera Sakti. Data resmi dapat menggantikan data
// ini kapan pun tanpa mengubah struktur aplikasi.
// ============================================================

export const DEMO_NOTICE = "Seluruh data pada prototype ini adalah DATA SIMULASI dan bukan data resmi organisasi.";

export const orgStats = {
  members: 324581,
  provinces: 34,
  branches: 421,
  rantings: 2843,
  activeMembers: 287420,
  pending: 142,
  countries: 8,
};

// ---------------- SEJARAH ----------------
export const historicalTimeline = [
  {
    year: "Awal Perjalanan",
    era: "1980-an",
    title: "Awal Perjalanan ",
    description:
      "Organisasi ini lahir dari semangat melestarikan ilmu bela diri serta membina generasi muda. Momentum awal perjalanan — nama, tempat, dan tokoh pendiri menunggu data resmi.",
    tag: "Berawal dari sebuah tekad",
    dataNote: true,
  },
  {
    era: "1980-an — 1990-an",
    year: "Pembinaan & Kaderisasi",
    title: "Pembinaan dan Kaderisasi ",
    description:
      "Latihan rutin, pembentukan kader, dan ujian kenaikan tingkat mulai diselenggarakan secara terstruktur. Generasi pertama pelatih dibentuk pada masa ini.",
    tag: "Fondasi kaderisasi",
    dataNote: true,
  },
  {
    era: "1990-an — 2000-an",
    year: "Perluasan Wilayah",
    title: "Perluasan Wilayah ",
    description:
      "Organisasi tumbuh dari satu daerah ke berbagai provinsi. Cabang dan ranting dibentuk di kota-kota baru, membawa nilai persaudaraan ke seluruh Nusantara.",
    tag: "Dari lokal menuju nasional",
    dataNote: true,
  },
  {
    era: "2000-an — 2010-an",
    year: "Penguatan Organisasi",
    title: "Penguatan Organisasi ",
    description:
      "Struktur organisasi disempurnakan: kepengurusan pusat, pengurus daerah, cabang, hingga ranting. Kegiatan sosial, budaya, dan kompetisi semakin aktif.",
    tag: "Struktur yang semakin kokoh",
    dataNote: true,
  },
  {
    era: "2010-an — 2020-an",
    year: "Generasi ke Generasi",
    title: "Generasi ke Generasi ",
    description:
      "Kaderisasi berjalan dari generasi ke generasi. Anggota muda tumbuh menjadi pelatih dan pengurus, memastikan keberlanjutan nilai dan ilmu.",
    tag: "Regenerasi kepemimpinan",
    dataNote: true,
  },
  {
    era: "Hari Ini",
    year: "IKSPI Hari Ini",
    title: "Menuju Ekosistem Digital ",
    description:
      "IKSPI DIGITAL hadir sebagai rumah digital organisasi: identitas digital anggota, database terpusat, information center, dan transparansi organisasi.",
    tag: "Dari organisasi menuju ekosistem",
    dataNote: true,
  },
];

// ---------------- TOKOH / FIGURES ----------------
export const figures = [
  {
    name: "[Nama Pendiri]",
    role: "Pendiri Organisasi",
    period: "",
    description:
      "Perintis yang menanamkan nilai persaudaraan, kedisiplinan, dan cinta budaya. Data resmi nama dan riwayat menunggu konfirmasi pengurus pusat.",
    initials: "PS",
  },
  {
    name: "[Nama Ketua Umum]",
    role: "Ketua Umum — Masa Bakti [X]",
    period: "",
    description: "Pemimpin organisasi saat ini yang membawa arah penguatan struktur dan modernisasi organisasi.",
    initials: "KU",
  },
  {
    name: "[Nama Sekretaris Jenderal]",
    role: "Sekretaris Jenderal",
    period: "",
    description: "Penggerak administrasi, kaderisasi kepengurusan, dan tata kelola organisasi secara nasional.",
    initials: "SG",
  },
  {
    name: "[Nama Pembina]",
    role: "Ketua Dewan Pembina",
    period: "",
    description: "Sesepuh yang menjaga kemurnian nilai, filosofi, dan arah pembinaan organisasi dari masa ke masa.",
    initials: "PB",
  },
  {
    name: "[Nama Pelatih Nasional]",
    role: "Pelatih / Instruktur Nasional",
    period: "",
    description:
      "Tokoh yang membina para pelatih dan atlet di berbagai cabang, menjaga kualitas latihan di seluruh Indonesia.",
    initials: "PL",
  },
  {
    name: "[Nama Tokoh Muda]",
    role: "Perwakilan Generasi Muda",
    period: "",
    description: "Wajah generasi penerus yang aktif membawa organisasi ke dunia digital dan menjangkau anak muda.",
    initials: "GM",
  },
];

// ---------------- NILAI & FILOSOFI ----------------
export const values = [
  {
    icon: "handshake",
    title: "Persaudaraan",
    description:
      "Satu persaudaraan di atas segalanya. Anggota adalah keluarga besar yang saling menjaga, di mana pun berada.",
  },
  {
    icon: "shield",
    title: "Disiplin",
    description:
      "Latihan yang tekun dan kepatuhan pada aturan membentuk pribadi yang tertib, baik di dalam maupun di luar organisasi.",
  },
  {
    icon: "flame",
    title: "Keberanian",
    description: "Berani membela kebenaran, berani melangkah, dan berani bertanggung jawab atas setiap pilihan.",
  },
  {
    icon: "sprout",
    title: "Kerendahan Hati",
    description: "Semakin tinggi ilmu, semakin merunduk. Rendah hati adalah ciri orang yang benar-benar berlatih.",
  },
  {
    icon: "scale",
    title: "Tanggung Jawab",
    description: "Setiap anggota memikul tanggung jawab: terhadap diri sendiri, keluarga, masyarakat, dan organisasi.",
  },
  {
    icon: "compass",
    title: "Pengendalian Diri",
    description: "Ilmu bela diri sejati dimulai dari kemampuan mengendalikan diri — emosi, ucapan, dan tindakan.",
  },
];

// ---------------- WHAT WE DO ----------------
export const activities = [
  {
    title: "Latihan Rutin",
    category: "Pembinaan",
    description: "Latihan fisik, teknik, dan jurus secara terjadwal di seluruh cabang dan ranting.",
    image: "/images/silat-indonesia.jpg",
  },
  {
    title: "Pembinaan Anggota",
    category: "Kaderisasi",
    description: "Pembinaan karakter dan keterampilan anggota secara berjenjang dari muda hingga dewasa.",
    image: "/images/aktivitas-latihan.jpg",
  },
  {
    title: "Ujian Kenaikan Tingkat",
    category: "Pembinaan",
    description: "Evaluasi dan pengakuan kemajuan anggota melalui ujian tingkat yang terstruktur.",
    image: "/images/silat-air.jpg",
  },
  {
    title: "Kegiatan Organisasi",
    category: "Organisasi",
    description: "Rapat kerja, musyawarah daerah, dan konsolidasi kepengurusan di semua tingkatan.",
    image: "/images/silat-betawi.jpg",
  },
  {
    title: "Kegiatan Sosial",
    category: "Kemasyarakatan",
    description: "Bakti sosial, donor darah, dan aksi kemanusiaan sebagai wujud pengabdian kepada masyarakat.",
    image: "/images/silat-nusantara.jpg",
  },
  {
    title: "Kegiatan Budaya",
    category: "Budaya",
    description: "Pelestarian seni bela diri sebagai warisan budaya bangsa melalui pagelaran dan kolaborasi.",
    image: "/images/silat-jabar.jpg",
  },
  {
    title: "Kompetisi & Kejuaraan",
    category: "Prestasi",
    description: "Keikutsertaan dalam kejuaraan nasional maupun internasional sebagai pembuktian kualitas.",
    image: "/images/silat-indonesia-2.jpg",
  },
  {
    title: "Pendidikan Karakter",
    category: "Pembinaan",
    description: "Pembentukan mental, etika, dan kedisiplinan generasi muda melalui nilai-nilai luhur.",
    image: "/images/silat-indonesia.jpg",
  },
  {
    title: "Komunitas & Silaturahmi",
    category: "Kemasyarakatan",
    description: "Mempererat hubungan antaranggota dan masyarakat melalui kegiatan kebersamaan.",
    image: "/images/aktivitas-latihan.jpg",
  },
];

// ---------------- KEGIATAN / EVENTS ----------------
export const events = [
  {
    id: "evt-001",
    title: "Latihan Bersama Nasional — Sabtu Merah Putih",
    category: "Latihan Bersama",
    date: "2026-10-12",
    location: "Stadion Utama, Jakarta",
    description: "Latihan bersama anggota dari seluruh pengda se-Jabodetabek. Terbuka untuk seluruh jenjang.",
    image: "/images/silat-indonesia.jpg",
    status: "open",
  },
  {
    id: "evt-002",
    title: "Ujian Kenaikan Tingkat Periode II",
    category: "Ujian",
    date: "2026-10-25",
    location: "Cabang Jawa Tengah",
    description: "Ujian kenaikan tingkat untuk anggota jenjang muda hingga utama di wilayah Jawa Tengah.",
    image: "/images/silat-air.jpg",
    status: "open",
  },
  {
    id: "evt-003",
    title: "Kejuaraan Pencak Silat Antar Cabang",
    category: "Kejuaraan",
    date: "2026-11-08",
    location: "GOR Surya Kencana, Bogor",
    description: "Kompetisi antar cabang memperebutkan piala Ketua Umum. Kategori tanding dan seni.",
    image: "/images/silat-indonesia-2.jpg",
    status: "open",
  },
  {
    id: "evt-004",
    title: "Bakti Sosial & Donor Darah Nasional",
    category: "Sosial",
    date: "2026-11-21",
    location: "Serentak di 34 provinsi",
    description: "Aksi kemanusiaan serentak: donor darah, santunan, dan bakti sosial di seluruh Indonesia.",
    image: "/images/silat-nusantara.jpg",
    status: "open",
  },
  {
    id: "evt-005",
    title: "Seminar Nasional: Bela Diri & Pendidikan Karakter",
    category: "Seminar",
    date: "2026-12-05",
    location: "Aula Pusat, Yogyakarta",
    description: "Diskusi tentang peran bela diri dalam pembentukan karakter generasi muda.",
    image: "/images/silat-betawi.jpg",
    status: "open",
  },
  {
    id: "evt-006",
    title: "Pagelaran Budaya Nusantara",
    category: "Budaya",
    date: "2026-12-19",
    location: "Taman Budaya, Surabaya",
    description: "Pagelaran seni bela diri dan budaya kolaborasi dengan komunitas seni lokal.",
    image: "/images/silat-jabar.jpg",
    status: "open",
  },
];

// ---------------- BERITA / NEWS ----------------
export const news = [
  {
    id: "nws-001",
    title: "IKSPI DIGITAL Resmi Diperkenalkan: Rumah Digital Organisasi",
    category: "Berita",
    date: "2026-09-01",
    author: "Tim Media IKSPI",
    featured: true,
    excerpt:
      "Organisasi mengambil langkah besar menuju era digital dengan menghadirkan ekosistem digital terpadu: identitas digital anggota, database organisasi, dan pusat informasi resmi.",
    image: "/images/hero-anggota.png",
  },
  {
    id: "nws-002",
    title: "324 Ribu Lebih Anggota Tersebar di Seluruh Indonesia ",
    category: "Organisasi",
    date: "2026-08-27",
    author: "Sekretariat",
    featured: false,
    excerpt:
      "Data simulasi menunjukkan besarnya ekosistem organisasi: ratusan cabang dan ribuan ranting dari Sabang sampai Merauke.",
    image: "/images/silat-indonesia.jpg",
  },
  {
    id: "nws-003",
    title: "Pengumuman: Pendaftaran Anggota Baru Gelombang III Dibuka",
    category: "Pengumuman",
    date: "2026-08-20",
    author: "Sekretariat",
    featured: false,
    excerpt:
      "Pendaftaran anggota baru gelombang ketiga dibuka secara online melalui portal IKSPI DIGITAL. Kuota terbatas.",
    image: "/images/silat-air.jpg",
  },
  {
    id: "nws-004",
    title: "Tim Indonesia Raih Prestasi di Kejuaraan Internasional ",
    category: "Prestasi",
    date: "2026-08-11",
    author: "Bidang Prestasi",
    featured: false,
    excerpt:
      "Atlet binaan mencatatkan prestasi membanggakan pada kejuaraan internasional. Detail resmi menunggu data resmi.",
    image: "/images/silat-indonesia-2.jpg",
  },
  {
    id: "nws-005",
    title: "Rakerpim 2026: Menyusun Arah Organisasi Lima Tahun ke Depan",
    category: "Organisasi",
    date: "2026-07-28",
    author: "Sekretariat",
    featured: false,
    excerpt: "Rapat Kerja Pimpinan membahas program kerja, penguatan cabang, dan transformasi digital organisasi.",
    image: "/images/silat-betawi.jpg",
  },
  {
    id: "nws-006",
    title: "Jadwal Ujian Kenaikan Tingkat Semester II Diumumkan",
    category: "Pengumuman",
    date: "2026-07-15",
    author: "Bidang Pembinaan",
    featured: false,
    excerpt:
      "Jadwal ujian kenaikan tingkat untuk seluruh pengda telah diterbitkan dan dapat diakses melalui pusat informasi.",
    image: "/images/silat-nusantara.jpg",
  },
  {
    id: "nws-007",
    title: "Bakti Sosial Serentak: Ribuan Anggota Bergerak untuk Masyarakat",
    category: "Kegiatan",
    date: "2026-07-02",
    author: "Bidang Sosial",
    featured: false,
    excerpt: "Kegiatan bakti sosial dan donor darah serentak menjadi wujud pengabdian organisasi kepada masyarakat.",
    image: "/images/silat-jabar.jpg",
  },
  {
    id: "nws-008",
    title: "Regenerasi: 200+ Pelatih Muda Mengikuti Pembinaan Instruktur",
    category: "Kegiatan",
    date: "2026-06-18",
    author: "Bidang Pembinaan",
    featured: false,
    excerpt: "Pembinaan instruktur muda diharapkan memperkuat kualitas latihan di cabang dan ranting.",
    image: "/images/aktivitas-latihan.jpg",
  },
];

// ---------------- PRESTASI ----------------
export const achievements = [
  {
    id: "ach-001",
    title: "Juara Umum Kejuaraan Regional",
    event: "Kejuaraan Bela Diri Nusantara",
    year: "2025",
    level: "Regional",
    medal: "gold",
  },
  {
    id: "ach-002",
    title: "Medali Emas Kategori Tanding",
    event: "Kejuaraan Nasional",
    year: "2024",
    level: "Nasional",
    medal: "gold",
  },
  {
    id: "ach-003",
    title: "Perak Seni Tunggal",
    event: "Festival Seni Bela Diri",
    year: "2024",
    level: "Nasional",
    medal: "silver",
  },
  {
    id: "ach-004",
    title: "Perunggu Kategori Beregu",
    event: "Kejuaraan Internasional ",
    year: "2023",
    level: "Internasional",
    medal: "bronze",
  },
  {
    id: "ach-005",
    title: "Pengakuan Organisasi Teraktif Bidang Kaderisasi",
    event: "Anugerah Organisasi",
    year: "2023",
    level: "Nasional",
    medal: "gold",
  },
];

// ---------------- PROVINSI (untuk peta & sebaran) ----------------
export const provinces = [
  { name: "Aceh", geojson: "DI. ACEH", members: 6100, branches: 11, rantings: 82, capital: "Banda Aceh" },
  { name: "Sumatera Utara", geojson: "SUMATERA UTARA", members: 15200, branches: 19, rantings: 138, capital: "Medan" },
  { name: "Sumatera Barat", geojson: "SUMATERA BARAT", members: 11800, branches: 15, rantings: 96, capital: "Padang" },
  { name: "Riau", geojson: "RIAU", members: 9600, branches: 12, rantings: 74, capital: "Pekanbaru" },
  { name: "Jambi", geojson: "JAMBI", members: 5400, branches: 8, rantings: 51, capital: "Jambi" },
  {
    name: "Sumatera Selatan",
    geojson: "SUMATERA SELATAN",
    members: 10800,
    branches: 13,
    rantings: 89,
    capital: "Palembang",
  },
  { name: "Bengkulu", geojson: "BENGKULU", members: 3600, branches: 6, rantings: 38, capital: "Bengkulu" },
  { name: "Lampung", geojson: "LAMPUNG", members: 9400, branches: 12, rantings: 77, capital: "Bandar Lampung" },
  {
    name: "Kep. Bangka Belitung",
    geojson: "BANGKA BELITUNG",
    members: 2300,
    branches: 4,
    rantings: 26,
    capital: "Pangkalpinang",
  },
  { name: "Kep. Riau", geojson: null, members: 4100, branches: 5, rantings: 30, capital: "Tanjungpinang" },
  { name: "DKI Jakarta", geojson: "DKI JAKARTA", members: 24500, branches: 24, rantings: 168, capital: "Jakarta" },
  { name: "Jawa Barat", geojson: "JAWA BARAT", members: 42100, branches: 41, rantings: 310, capital: "Bandung" },
  { name: "Banten", geojson: "PROBANTEN", members: 15600, branches: 17, rantings: 121, capital: "Serang" },
  { name: "Jawa Tengah", geojson: "JAWA TENGAH", members: 38900, branches: 37, rantings: 284, capital: "Semarang" },
  {
    name: "DI Yogyakarta",
    geojson: "DAERAH ISTIMEWA YOGYAKARTA",
    members: 7200,
    branches: 8,
    rantings: 57,
    capital: "Yogyakarta",
  },
  { name: "Jawa Timur", geojson: "JAWA TIMUR", members: 45300, branches: 44, rantings: 352, capital: "Surabaya" },
  { name: "Bali", geojson: "BALI", members: 6800, branches: 7, rantings: 48, capital: "Denpasar" },
  {
    name: "Nusa Tenggara Barat",
    geojson: "NUSATENGGARA BARAT",
    members: 5200,
    branches: 7,
    rantings: 44,
    capital: "Mataram",
  },
  {
    name: "Nusa Tenggara Timur",
    geojson: "NUSA TENGGARA TIMUR",
    members: 4600,
    branches: 6,
    rantings: 41,
    capital: "Kupang",
  },
  {
    name: "Kalimantan Barat",
    geojson: "KALIMANTAN BARAT",
    members: 6100,
    branches: 8,
    rantings: 52,
    capital: "Pontianak",
  },
  {
    name: "Kalimantan Tengah",
    geojson: "KALIMANTAN TENGAH",
    members: 3800,
    branches: 6,
    rantings: 35,
    capital: "Palangka Raya",
  },
  {
    name: "Kalimantan Selatan",
    geojson: "KALIMANTAN SELATAN",
    members: 5400,
    branches: 7,
    rantings: 46,
    capital: "Banjarmasin",
  },
  {
    name: "Kalimantan Timur",
    geojson: "KALIMANTAN TIMUR",
    members: 6200,
    branches: 8,
    rantings: 53,
    capital: "Samarinda",
  },
  { name: "Kalimantan Utara", geojson: null, members: 1500, branches: 3, rantings: 18, capital: "Tanjung Selor" },
  { name: "Sulawesi Utara", geojson: "SULAWESI UTARA", members: 4900, branches: 6, rantings: 39, capital: "Manado" },
  { name: "Sulawesi Tengah", geojson: "SULAWESI TENGAH", members: 3800, branches: 5, rantings: 33, capital: "Palu" },
  {
    name: "Sulawesi Selatan",
    geojson: "SULAWESI SELATAN",
    members: 11700,
    branches: 14,
    rantings: 92,
    capital: "Makassar",
  },
  {
    name: "Sulawesi Tenggara",
    geojson: "SULAWESI TENGGARA",
    members: 4100,
    branches: 6,
    rantings: 36,
    capital: "Kendari",
  },
  { name: "Sulawesi Barat", geojson: null, members: 1900, branches: 4, rantings: 22, capital: "Mamuju" },
  { name: "Gorontalo", geojson: "GORONTALO", members: 1600, branches: 3, rantings: 17, capital: "Gorontalo" },
  { name: "Maluku", geojson: "MALUKU", members: 2900, branches: 5, rantings: 27, capital: "Ambon" },
  { name: "Maluku Utara", geojson: "MALUKU UTARA", members: 2100, branches: 4, rantings: 21, capital: "Sofifi" },
  { name: "Papua Barat", geojson: "IRIAN JAYA BARAT", members: 1300, branches: 3, rantings: 14, capital: "Manokwari" },
  { name: "Papua", geojson: "IRIAN JAYA TIMUR", members: 2200, branches: 4, rantings: 20, capital: "Jayapura" },
];

// Mapping GeoJSON name -> canonical province name
export const geojsonNameMap = Object.fromEntries(
  provinces.filter((p) => p.geojson).map((p) => [p.geojson.toUpperCase(), p.name]),
);

// ---------------- MEMBERS ----------------
export const jenjangList = [
  "Anggota Muda",
  "Anggota Madya",
  "Anggota Utama",
  "Pendekar Muda",
  "Pendekar Madya",
  "Pendekar Utama",
];

export const members = [
  {
    id: "mbr-001",
    nomor: "IKS.2021.01842",
    name: "Budi Santoso",
    gender: "L",
    province: "Jawa Timur",
    cabang: "Madiun",
    ranting: "Kota Madiun",
    jenjang: "Pendekar Muda",
    status: "AKTIF",
    joinYear: 2021,
    phone: "0812-3456-7890",
    birthDate: "1998-03-14",
    achievements: ["Juara 1 Kejuaraan Cabang 2023", "Peserta Kejuaraan Nasional 2024"],
    activities: ["Latihan Bersama", "Ujian Kenaikan Tingkat", "Bakti Sosial"],
  },
  {
    id: "mbr-002",
    nomor: "IKS.2019.00715",
    name: "Siti Rahmawati",
    gender: "P",
    province: "Jawa Barat",
    cabang: "Bandung",
    ranting: "Cicendo",
    jenjang: "Anggota Utama",
    status: "AKTIF",
    joinYear: 2019,
    phone: "0813-2233-4455",
    birthDate: "2001-07-22",
    achievements: ["Medali Perak Seni Tunggal 2024"],
    activities: ["Kejuaraan", "Seminar", "Pagelaran Budaya"],
  },
  {
    id: "mbr-003",
    nomor: "IKS.2015.00298",
    name: "Agus Wijaya",
    gender: "L",
    province: "DKI Jakarta",
    cabang: "Jakarta Pusat",
    ranting: "Senen",
    jenjang: "Pendekar Madya",
    status: "AKTIF",
    joinYear: 2015,
    phone: "0821-9988-7766",
    birthDate: "1990-11-02",
    achievements: ["Juara Umum Kejuaraan Regional 2025"],
    activities: ["Kejuaraan", "Pembinaan Instruktur"],
  },
  {
    id: "mbr-004",
    nomor: "IKS.2022.03117",
    name: "Dewi Lestari",
    gender: "P",
    province: "Jawa Tengah",
    cabang: "Semarang",
    ranting: "Banyumanik",
    jenjang: "Anggota Madya",
    status: "AKTIF",
    joinYear: 2022,
    phone: "0857-1122-3344",
    birthDate: "2004-05-09",
    achievements: [],
    activities: ["Latihan Rutin", "Bakti Sosial"],
  },
  {
    id: "mbr-005",
    nomor: "IKS.2018.01122",
    name: "Rahmat Hidayat",
    gender: "L",
    province: "Sumatera Utara",
    cabang: "Medan",
    ranting: "Medan Kota",
    jenjang: "Anggota Utama",
    status: "AKTIF",
    joinYear: 2018,
    phone: "0811-6655-4433",
    birthDate: "1995-12-30",
    achievements: ["Juara 2 Kejuaraan Cabang 2024"],
    activities: ["Kejuaraan", "Ujian Kenaikan Tingkat"],
  },
  {
    id: "mbr-006",
    nomor: "IKS.2020.02456",
    name: "Aisyah Nurjanah",
    gender: "P",
    province: "Banten",
    cabang: "Tangerang",
    ranting: "Ciputat",
    jenjang: "Anggota Madya",
    status: "AKTIF",
    joinYear: 2020,
    phone: "0856-7788-9900",
    birthDate: "2002-01-17",
    achievements: [],
    activities: ["Latihan Bersama", "Kegiatan Sosial"],
  },
  {
    id: "mbr-007",
    nomor: "IKS.2016.00487",
    name: "Yudi Pratama",
    gender: "L",
    province: "Sulawesi Selatan",
    cabang: "Makassar",
    ranting: "Panakkukang",
    jenjang: "Pendekar Muda",
    status: "AKTIF",
    joinYear: 2016,
    phone: "0812-4455-6677",
    birthDate: "1992-09-25",
    achievements: ["Medali Emas Kategori Tanding 2024"],
    activities: ["Kejuaraan", "Pembinaan Instruktur"],
  },
  {
    id: "mbr-008",
    nomor: "IKS.2023.04021",
    name: "Fitri Handayani",
    gender: "P",
    province: "Bali",
    cabang: "Denpasar",
    ranting: "Denpasar Barat",
    jenjang: "Anggota Muda",
    status: "AKTIF",
    joinYear: 2023,
    phone: "0819-3344-5566",
    birthDate: "2005-08-11",
    achievements: [],
    activities: ["Latihan Rutin", "Pagelaran Budaya"],
  },
  {
    id: "mbr-009",
    nomor: "IKS.2017.00893",
    name: "Hendra Gunawan",
    gender: "L",
    province: "Kalimantan Timur",
    cabang: "Samarinda",
    ranting: "Samarinda Ulu",
    jenjang: "Anggota Utama",
    status: "NON-AKTIF",
    joinYear: 2017,
    phone: "0822-5566-7788",
    birthDate: "1994-04-03",
    achievements: [],
    activities: ["Ujian Kenaikan Tingkat"],
  },
  {
    id: "mbr-010",
    nomor: "IKS.2014.00112",
    name: "Joko Susilo",
    gender: "L",
    province: "DI Yogyakarta",
    cabang: "Kota Yogyakarta",
    ranting: "Gondokusuman",
    jenjang: "Pendekar Utama",
    status: "AKTIF",
    joinYear: 2014,
    phone: "0878-1122-3344",
    birthDate: "1986-06-19",
    achievements: ["Pengakuan Organisasi Teraktif 2023"],
    activities: ["Pembinaan Instruktur", "Seminar"],
  },
  {
    id: "mbr-011",
    nomor: "IKS.2024.04512",
    name: "Rina Marlina",
    gender: "P",
    province: "Jawa Barat",
    cabang: "Bogor",
    ranting: "Bogor Timur",
    jenjang: "Anggota Muda",
    status: "AKTIF",
    joinYear: 2024,
    phone: "0815-6677-8899",
    birthDate: "2006-02-27",
    achievements: [],
    activities: ["Latihan Rutin"],
  },
  {
    id: "mbr-012",
    nomor: "IKS.2019.01308",
    name: "Andi Saputra",
    gender: "L",
    province: "Riau",
    cabang: "Pekanbaru",
    ranting: "Tampan",
    jenjang: "Anggota Utama",
    status: "AKTIF",
    joinYear: 2019,
    phone: "0813-8899-0011",
    birthDate: "1997-10-08",
    achievements: ["Juara 3 Kejuaraan Regional 2024"],
    activities: ["Kejuaraan", "Bakti Sosial"],
  },
  {
    id: "mbr-013",
    nomor: "IKS.2018.01477",
    name: "Nur Aini",
    gender: "P",
    province: "Lampung",
    cabang: "Bandar Lampung",
    ranting: "Tanjung Karang",
    jenjang: "Anggota Madya",
    status: "AKTIF",
    joinYear: 2018,
    phone: "0852-2233-4455",
    birthDate: "2000-12-05",
    achievements: [],
    activities: ["Latihan Bersama", "Kegiatan Sosial"],
  },
  {
    id: "mbr-014",
    nomor: "IKS.2015.00634",
    name: "Slamet Riyadi",
    gender: "L",
    province: "Jawa Tengah",
    cabang: "Solo",
    ranting: "Banjarsari",
    jenjang: "Pendekar Madya",
    status: "AKTIF",
    joinYear: 2015,
    phone: "0812-9988-7766",
    birthDate: "1989-03-21",
    achievements: ["Medali Perak Beregu 2023"],
    activities: ["Pembinaan Instruktur", "Kejuaraan"],
  },
  {
    id: "mbr-015",
    nomor: "IKS.2021.01933",
    name: "Maya Puspita",
    gender: "P",
    province: "Sumatera Barat",
    cabang: "Padang",
    ranting: "Padang Utara",
    jenjang: "Anggota Madya",
    status: "AKTIF",
    joinYear: 2021,
    phone: "0853-4455-6677",
    birthDate: "2003-09-14",
    achievements: [],
    activities: ["Ujian Kenaikan Tingkat"],
  },
  {
    id: "mbr-016",
    nomor: "IKS.2020.02890",
    name: "Fajar Nugroho",
    gender: "L",
    province: "Nusa Tenggara Barat",
    cabang: "Mataram",
    ranting: "Cakranegara",
    jenjang: "Anggota Utama",
    status: "AKTIF",
    joinYear: 2020,
    phone: "0817-6677-8899",
    birthDate: "1999-07-01",
    achievements: [],
    activities: ["Latihan Bersama", "Bakti Sosial"],
  },
  {
    id: "mbr-017",
    nomor: "IKS.2016.00912",
    name: "Wawan Kurniawan",
    gender: "L",
    province: "Kalimantan Selatan",
    cabang: "Banjarmasin",
    ranting: "Banjarmasin Tengah",
    jenjang: "Pendekar Muda",
    status: "AKTIF",
    joinYear: 2016,
    phone: "0823-1122-3344",
    birthDate: "1991-11-11",
    achievements: ["Juara 2 Kejuaraan Regional 2023"],
    activities: ["Kejuaraan", "Ujian Kenaikan Tingkat"],
  },
  {
    id: "mbr-018",
    nomor: "IKS.2022.03544",
    name: "Intan Permata",
    gender: "P",
    province: "DKI Jakarta",
    cabang: "Jakarta Timur",
    ranting: "Duren Sawit",
    jenjang: "Anggota Muda",
    status: "AKTIF",
    joinYear: 2022,
    phone: "0811-2233-4455",
    birthDate: "2005-04-28",
    achievements: [],
    activities: ["Latihan Rutin", "Pagelaran Budaya"],
  },
  {
    id: "mbr-019",
    nomor: "IKS.2013.00087",
    name: "Hasan Basri",
    gender: "L",
    province: "Aceh",
    cabang: "Banda Aceh",
    ranting: "Baiturrahman",
    jenjang: "Pendekar Utama",
    status: "AKTIF",
    joinYear: 2013,
    phone: "0851-6677-8899",
    birthDate: "1984-01-15",
    achievements: ["Pengakuan Kaderisasi Terbaik 2022"],
    activities: ["Pembinaan Instruktur", "Seminar"],
  },
  {
    id: "mbr-020",
    nomor: "IKS.2024.04871",
    name: "Putri Amelia",
    gender: "P",
    province: "Sulawesi Utara",
    cabang: "Manado",
    ranting: "Wanea",
    jenjang: "Anggota Muda",
    status: "PENDING",
    joinYear: 2024,
    phone: "0856-9988-7766",
    birthDate: "2007-06-30",
    achievements: [],
    activities: ["Latihan Rutin"],
  },
];

// ---------------- REGISTRASI (pending) ----------------
export const registrations = [
  {
    id: "reg-001",
    nomor: "REG-2026-00001",
    name: "Bayu Aji Pamungkas",
    province: "Jawa Timur",
    cabang: "Madiun",
    ranting: "Kota Madiun",
    jenjang: "Anggota Muda",
    submittedAt: "2026-08-30",
    status: "MENUNGGU",
    phone: "0812-7788-9900",
    birthDate: "2004-02-18",
    gender: "L",
  },
  {
    id: "reg-002",
    nomor: "REG-2026-00002",
    name: "Salsa Dwi Anjani",
    province: "Jawa Barat",
    cabang: "Bandung",
    ranting: "Coblong",
    jenjang: "Anggota Muda",
    submittedAt: "2026-08-31",
    status: "MENUNGGU",
    phone: "0813-4455-6677",
    birthDate: "2005-10-03",
    gender: "P",
  },
  {
    id: "reg-003",
    nomor: "REG-2026-00003",
    name: "Rizky Ramadhan",
    province: "Sumatera Selatan",
    cabang: "Palembang",
    ranting: "Ilir Timur",
    jenjang: "Anggota Muda",
    submittedAt: "2026-09-01",
    status: "MENUNGGU",
    phone: "0821-5566-7788",
    birthDate: "2003-08-25",
    gender: "L",
  },
  {
    id: "reg-004",
    nomor: "REG-2026-00004",
    name: "Laila Fitriani",
    province: "Kalimantan Timur",
    cabang: "Balikpapan",
    ranting: "Balikpapan Kota",
    jenjang: "Anggota Muda",
    submittedAt: "2026-09-02",
    status: "MENUNGGU",
    phone: "0852-1122-3344",
    birthDate: "2006-12-09",
    gender: "P",
  },
  {
    id: "reg-005",
    nomor: "REG-2026-00005",
    name: "Dimas Anggara",
    province: "Nusa Tenggara Timur",
    cabang: "Kupang",
    ranting: "Kota Kupang",
    jenjang: "Anggota Muda",
    submittedAt: "2026-09-03",
    status: "MENUNGGU",
    phone: "0819-2233-4455",
    birthDate: "2004-05-17",
    gender: "L",
  },
];

// ---------------- STRUKTUR ORGANISASI ----------------
export const organizationTree = {
  name: "IKSPI Pusat",
  type: "Pusat",
  detail: "Kepengurusan Pusat ",
  children: [
    {
      name: "Pengda Jawa Timur",
      type: "Pengda",
      detail: "34 cabang",
      children: [
        {
          name: "Cabang Madiun",
          type: "Cabang",
          detail: "8 ranting",
          children: [
            { name: "Ranting Kota Madiun", type: "Ranting", detail: "142 anggota" },
            { name: "Ranting Madiun Barat", type: "Ranting", detail: "98 anggota" },
            { name: "Ranting Mejayan", type: "Ranting", detail: "76 anggota" },
          ],
        },
        {
          name: "Cabang Surabaya",
          type: "Cabang",
          detail: "9 ranting",
          children: [
            { name: "Ranting Gubeng", type: "Ranting", detail: "130 anggota" },
            { name: "Ranting Rungkut", type: "Ranting", detail: "112 anggota" },
          ],
        },
        { name: "Cabang Malang", type: "Cabang", detail: "6 ranting" },
        { name: "Cabang Kediri", type: "Cabang", detail: "5 ranting" },
      ],
    },
    {
      name: "Pengda Jawa Barat",
      type: "Pengda",
      detail: "41 cabang",
      children: [
        { name: "Cabang Bandung", type: "Cabang", detail: "7 ranting" },
        { name: "Cabang Bogor", type: "Cabang", detail: "6 ranting" },
        { name: "Cabang Bekasi", type: "Cabang", detail: "5 ranting" },
      ],
    },
    {
      name: "Pengda DKI Jakarta",
      type: "Pengda",
      detail: "24 cabang",
      children: [
        { name: "Cabang Jakarta Pusat", type: "Cabang", detail: "5 ranting" },
        { name: "Cabang Jakarta Timur", type: "Cabang", detail: "4 ranting" },
      ],
    },
    {
      name: "Pengda Jawa Tengah",
      type: "Pengda",
      detail: "37 cabang",
      children: [
        { name: "Cabang Semarang", type: "Cabang", detail: "7 ranting" },
        { name: "Cabang Solo", type: "Cabang", detail: "6 ranting" },
        { name: "Cabang Purwokerto", type: "Cabang", detail: "4 ranting" },
      ],
    },
    {
      name: "Pengda Sumatera Utara",
      type: "Pengda",
      detail: "19 cabang",
      children: [{ name: "Cabang Medan", type: "Cabang", detail: "6 ranting" }],
    },
    {
      name: "Pengda Sulawesi Selatan",
      type: "Pengda",
      detail: "14 cabang",
      children: [{ name: "Cabang Makassar", type: "Cabang", detail: "5 ranting" }],
    },
  ],
};

// ---------------- PERTUMBUHAN ANGGOTA (chart) ----------------
export const growthData = [
  { year: "2016", anggota: 96200 },
  { year: "2017", anggota: 118500 },
  { year: "2018", anggota: 141800 },
  { year: "2019", anggota: 169300 },
  { year: "2020", anggota: 195600 },
  { year: "2021", anggota: 224900 },
  { year: "2022", anggota: 254700 },
  { year: "2023", anggota: 281300 },
  { year: "2024", anggota: 302800 },
  { year: "2025", anggota: 316400 },
  { year: "2026", anggota: 324581 },
];

export const jenjangDistribution = [
  { name: "Anggota Muda", value: 118200 },
  { name: "Anggota Madya", value: 96400 },
  { name: "Anggota Utama", value: 62400 },
  { name: "Pendekar Muda", value: 31200 },
  { name: "Pendekar Madya", value: 12100 },
  { name: "Pendekar Utama", value: 4281 },
];

export const statusDistribution = [
  { name: "Aktif", value: 287420 },
  { name: "Non-Aktif", value: 35019 },
  { name: "Menunggu Verifikasi", value: 2142 },
];

export const regionDistribution = [
  { name: "Jawa", value: 173700 },
  { name: "Sumatera", value: 78900 },
  { name: "Sulawesi", value: 28000 },
  { name: "Kalimantan", value: 23000 },
  { name: "Bali & Nusa Tenggara", value: 16600 },
  { name: "Maluku & Papua", value: 4381 },
];

// ---------------- ACTIVITY FEED ----------------
export const activityFeed = [
  {
    id: 1,
    actor: "Cabang Madiun",
    action: "membuka pendaftaran anggota baru",
    time: "10 menit lalu",
    type: "registrasi",
  },
  {
    id: 2,
    actor: "Pengda Jawa Timur",
    action: "mengumumkan jadwal ujian kenaikan tingkat",
    time: "1 jam lalu",
    type: "pengumuman",
  },
  {
    id: 3,
    actor: "Cabang Bandung",
    action: "melaporkan 12 anggota baru terverifikasi",
    time: "3 jam lalu",
    type: "anggota",
  },
  {
    id: 4,
    actor: "Bidang Prestasi",
    action: "memperbarui data kejuaraan nasional",
    time: "5 jam lalu",
    type: "prestasi",
  },
  {
    id: 5,
    actor: "Pengda Sumatera Utara",
    action: "menyelenggarakan bakti sosial di Medan",
    time: "8 jam lalu",
    type: "kegiatan",
  },
  {
    id: 6,
    actor: "Sekretariat Pusat",
    action: "menerbitkan pengumuman gelombang III",
    time: "1 hari lalu",
    type: "pengumuman",
  },
  {
    id: 7,
    actor: "Cabang Makassar",
    action: "mengunggah dokumentasi kejuaraan",
    time: "1 hari lalu",
    type: "kegiatan",
  },
  {
    id: 8,
    actor: "Pengda DKI Jakarta",
    action: "memperbarui struktur kepengurusan",
    time: "2 hari lalu",
    type: "organisasi",
  },
];

// ---------------- JENJANG DESKRIPSI ----------------
export const jenjangDescriptions = {
  "Anggota Muda": "Tahap awal pembinaan: pengenalan teknik dasar, disiplin latihan, dan nilai organisasi.",
  "Anggota Madya": "Penguasaan teknik lanjutan, jurus, dan keterlibatan aktif dalam kegiatan organisasi.",
  "Anggota Utama": "Kematangan teknik dan karakter, mulai membina anggota muda di lingkungannya.",
  "Pendekar Muda": "Kualifikasi pembinaan: mampu melatih, menguji, dan menjadi teladan di cabang.",
  "Pendekar Madya": "Pengabdian penuh: memimpin pembinaan dan pengembangan organisasi di tingkat daerah.",
  "Pendekar Utama": "Puncak pembinaan: menjaga kemurnian nilai, ilmu, dan keberlanjutan organisasi.",
};

// ---------------- AGENDA ----------------
export const agenda = [
  { date: "2026-10-12", title: "Latihan Bersama Nasional", type: "Kegiatan" },
  { date: "2026-10-25", title: "Ujian Kenaikan Tingkat", type: "Pembinaan" },
  { date: "2026-11-08", title: "Kejuaraan Antar Cabang", type: "Kompetisi" },
  { date: "2026-11-21", title: "Bakti Sosial Serentak", type: "Sosial" },
  { date: "2026-12-05", title: "Seminar Nasional", type: "Seminar" },
  { date: "2026-12-19", title: "Pagelaran Budaya Nusantara", type: "Budaya" },
];

// ---------------- MARQUEE ----------------
export const tickerItems = [
  "324.581 Anggota",
  "34 Provinsi",
  "421 Cabang",
  "2.843 Ranting",
  "Satu Persaudaraan",
  "Satu Keluarga",
  "Satu Ekosistem",
  "IKSPI DIGITAL",
];

export const photoCredits = [
  "Foto utama & latihan: dokumen kegiatan organisasi (ilustrasi).",
  "Foto pendukung: Wikimedia Commons (lisensi CC BY-SA) — Pencak Silat Air, Pencak Silat Nusantara, Pencak Silat Betawi, Pencak Silat Jawa Barat, Pencak Silat Indonesia, Indonesian Pencak Silat.",
  "Seluruh angka, nama, dan riwayat pada prototype adalah DATA SIMULASI.",
];
